Repository coffee-meet/backend, pull requests merged in 2023-11, with the labels that each got.

#74 배포 1.1
  Dockerfile
  README.md
  build.gradle
  src/main/java/coffeemeet/server/common/config/WebConfig.java
  src/test/java/coffeemeet/server/auth/controller/AuthControllerTest.java
  src/test/java/coffeemeet/server/common/config/ControllerTestConfig.java
  src/test/java/coffeemeet/server/user/controller/UserControllerTest.java
Labels: release

#85 채팅방 생성 및 채팅 기능 구현
  src/main/java/coffeemeet/server/auth/exception/AuthErrorCode.java
  src/main/java/coffeemeet/server/chatting/current/domain/ChattingMessage.java
  src/main/java/coffeemeet/server/chatting/current/domain/ChattingRoom.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingMessageCommand.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingRoomCommand.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingRoomQuery.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageRepository.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/ChattingRoomRepository.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingMessageController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatStomp.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingMessageService.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingRoomService.java
  src/main/java/coffeemeet/server/chatting/exception/ChattingErrorCode.java
  src/main/java/coffeemeet/server/common/config/ChattingConfig.java
  src/main/java/coffeemeet/server/common/execption/GlobalErrorCode.java
  src/main/java/coffeemeet/server/common/presentation/advice/GlobalExceptionHandler.java
  src/main/java/coffeemeet/server/common/presentation/interceptor/StompInterceptor.java
  src/main/java/coffeemeet/server/common/presentation/resolver/UserArgumentResolver.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingMessageCommandTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingRoomCommandTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingRoomQueryTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingMessageServiceTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingRoomServiceTest.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
Labels: feat

#89 배포 버전 0.2.1
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingMessageController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatStomp.java
  src/main/resources/application.yml
Labels: release

#94 채팅 메세지 서비스 기능 추가 및 리팩토링
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingMessageController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatStomp.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingMessageService.java
  src/main/java/coffeemeet/server/chatting/current/service/dto/ChattingDto.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingMessageServiceTest.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
Labels: feat

#97 채팅방 엔티티에 이름 필드 추가
  build.gradle
  src/main/java/coffeemeet/server/chatting/current/domain/ChattingRoom.java
Labels: feat

#100 채팅방 조회 기능 구현
  .github/workflows/ci.yml
  build.gradle
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingMessageQuery.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepository.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingMessageController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingRoomController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatStomp.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatsHTTP.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingRoomService.java
  src/main/java/coffeemeet/server/chatting/current/service/dto/ChattingDto.java
  src/main/java/coffeemeet/server/common/config/QueryDslConfig.java
  src/main/java/coffeemeet/server/common/config/WebConfig.java
  src/main/java/coffeemeet/server/common/execption/GlobalErrorCode.java
  src/main/java/coffeemeet/server/common/presentation/advice/GlobalExceptionHandler.java
  src/main/java/coffeemeet/server/common/presentation/interceptor/AuthenticationInterceptor.java
  src/test/java/coffeemeet/server/chatting/concurrency/ChattingMessageServiceConcurrencyTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingMessageQueryTest.java
  src/test/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepositoryTest.java
  src/test/java/coffeemeet/server/chatting/current/presentation/ChattingRoomControllerTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingRoomServiceTest.java
  src/test/java/coffeemeet/server/common/config/RepositoryTestConfig.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
  src/test/resources/application.yml
Labels: feat

#99 🦾 Refactor/#98 로그인 기능 리팩터링
  src/main/java/coffeemeet/server/user/presentation/UserController.java
  src/main/java/coffeemeet/server/user/presentation/dto/LoginDetailsHTTP.java
  src/main/java/coffeemeet/server/user/service/UserService.java
  src/main/java/coffeemeet/server/user/service/dto/LoginDetailsDto.java
  src/test/java/coffeemeet/server/common/fixture/dto/LoginDetailsDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/LoginDetailsHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/MyProfileDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/MyProfileHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/SignupHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/UpdateProfileHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/UserProfileHTTPFixture.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: refactor

#101 배포 버전 0.4.1
  .github/workflows/ci.yml
  build.gradle
  src/main/java/coffeemeet/server/chatting/current/domain/ChattingRoom.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingMessageQuery.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepository.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingMessageController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingRoomController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatStomp.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatsHTTP.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingRoomService.java
  src/main/java/coffeemeet/server/chatting/current/service/dto/ChattingDto.java
  src/main/java/coffeemeet/server/common/config/QueryDslConfig.java
  src/main/java/coffeemeet/server/common/config/WebConfig.java
  src/main/java/coffeemeet/server/common/execption/GlobalErrorCode.java
  src/main/java/coffeemeet/server/common/presentation/advice/GlobalExceptionHandler.java
  src/main/java/coffeemeet/server/common/presentation/interceptor/AuthenticationInterceptor.java
  src/main/java/coffeemeet/server/user/presentation/UserController.java
  src/main/java/coffeemeet/server/user/presentation/dto/LoginDetailsHTTP.java
  src/main/java/coffeemeet/server/user/service/UserService.java
  src/main/java/coffeemeet/server/user/service/dto/LoginDetailsDto.java
  src/test/java/coffeemeet/server/chatting/concurrency/ChattingMessageServiceConcurrencyTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingMessageQueryTest.java
  src/test/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepositoryTest.java
  src/test/java/coffeemeet/server/chatting/current/presentation/ChattingRoomControllerTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingRoomServiceTest.java
  src/test/java/coffeemeet/server/common/config/RepositoryTestConfig.java
  src/test/java/coffeemeet/server/common/fixture/dto/LoginDetailsDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/LoginDetailsHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/MyProfileDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/MyProfileHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/SignupHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/UpdateProfileHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/UserProfileHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: feat

#109 채팅 기능 리팩토링
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingMessageController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatStomp.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatsHTTP.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingMessageService.java
  src/main/java/coffeemeet/server/chatting/current/service/dto/ChattingDto.java
  src/main/java/coffeemeet/server/chatting/exception/ChattingErrorCode.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/implement/UserQuery.java
  src/main/java/coffeemeet/server/user/infrastructure/UserRepository.java
  src/test/java/coffeemeet/server/chatting/concurrency/ChattingMessageServiceConcurrencyTest.java
  src/test/java/coffeemeet/server/chatting/current/presentation/ChattingRoomControllerTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingMessageServiceTest.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/matching/presentation/MatchingControllerTest.java
Labels: refactor

#111 Feat/#110 누락된 유저 테스트 코드 작성
  src/test/java/coffeemeet/server/user/implement/UserCommandTest.java
  src/test/java/coffeemeet/server/user/implement/UserQueryTest.java
  src/test/java/coffeemeet/server/user/infrastructure/UserRepositoryTest.java
Labels: docs

#112 채팅방 나가기 기능 구현
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingMessageCommand.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingMessageQuery.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingRoomCommand.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepository.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingRoomController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatStomp.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatsHTTP.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingMessageService.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingRoomService.java
  src/main/java/coffeemeet/server/chatting/current/service/dto/ChattingDto.java
  src/main/java/coffeemeet/server/chatting/history/domain/ChattingRoomHistory.java
  src/main/java/coffeemeet/server/chatting/history/implement/ChattingMessageHistoryCommand.java
  src/main/java/coffeemeet/server/chatting/history/implement/ChattingRoomHistoryCommand.java
  src/main/java/coffeemeet/server/chatting/history/implement/UserChattingHistoryCommand.java
  src/main/java/coffeemeet/server/chatting/history/infrastructure/ChattingMessageHistoryRepository.java
  src/main/java/coffeemeet/server/chatting/history/infrastructure/ChattingRoomHistoryRepository.java
  src/main/java/coffeemeet/server/chatting/history/infrastructure/UserChattingHistoryRepository.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/domain/UserStatus.java
  src/test/java/coffeemeet/server/chatting/concurrency/ChattingMessageServiceConcurrencyTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingMessageCommandTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingMessageQueryTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingRoomCommandTest.java
  src/test/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepositoryTest.java
  src/test/java/coffeemeet/server/chatting/current/presentation/ChattingRoomControllerTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingMessageServiceTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingRoomServiceTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/ChattingMessageHistoryCommandTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/ChattingRoomHistoryCommandTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/UserChattingHistoryCommandTest.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
Labels: feat

#113 배포 버전 0.5.1
  src/main/java/coffeemeet/server/certification/implement/CertificationQuery.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingMessageCommand.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingMessageQuery.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingRoomCommand.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepository.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingMessageController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingRoomController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatStomp.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatsHTTP.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingMessageService.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingRoomService.java
  src/main/java/coffeemeet/server/chatting/current/service/dto/ChattingDto.java
  src/main/java/coffeemeet/server/chatting/exception/ChattingErrorCode.java
  src/main/java/coffeemeet/server/chatting/history/domain/ChattingRoomHistory.java
  src/main/java/coffeemeet/server/chatting/history/implement/ChattingMessageHistoryCommand.java
  src/main/java/coffeemeet/server/chatting/history/implement/ChattingRoomHistoryCommand.java
  src/main/java/coffeemeet/server/chatting/history/implement/UserChattingHistoryCommand.java
  src/main/java/coffeemeet/server/chatting/history/infrastructure/ChattingMessageHistoryRepository.java
  src/main/java/coffeemeet/server/chatting/history/infrastructure/ChattingRoomHistoryRepository.java
  src/main/java/coffeemeet/server/chatting/history/infrastructure/UserChattingHistoryRepository.java
  src/main/java/coffeemeet/server/common/config/RedisConfig.java
  src/main/java/coffeemeet/server/common/execption/RedisException.java
  src/main/java/coffeemeet/server/common/implement/FCMNotificationSender.java
  src/main/java/coffeemeet/server/matching/implement/MatchingQueueCommand.java
  src/main/java/coffeemeet/server/matching/implement/MatchingQueueQuery.java
  src/main/java/coffeemeet/server/matching/presentation/MatchingController.java
  src/main/java/coffeemeet/server/matching/service/MatchingService.java
  src/main/java/coffeemeet/server/user/domain/Email.java
  src/main/java/coffeemeet/server/user/domain/Profile.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/domain/UserStatus.java
  src/main/java/coffeemeet/server/user/implement/UserCommand.java
  src/main/java/coffeemeet/server/user/implement/UserQuery.java
  src/main/java/coffeemeet/server/user/infrastructure/UserRepository.java
  src/main/java/coffeemeet/server/user/presentation/UserController.java
  src/main/java/coffeemeet/server/user/service/dto/MyProfileDto.java
  src/test/java/coffeemeet/server/certification/infrastructure/CertificationRepositoryTest.java
  src/test/java/coffeemeet/server/chatting/concurrency/ChattingMessageServiceConcurrencyTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingMessageCommandTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingMessageQueryTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingRoomCommandTest.java
  src/test/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepositoryTest.java
  src/test/java/coffeemeet/server/chatting/current/presentation/ChattingRoomControllerTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingMessageServiceTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingRoomServiceTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/ChattingMessageHistoryCommandTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/ChattingRoomHistoryCommandTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/UserChattingHistoryCommandTest.java
  src/test/java/coffeemeet/server/common/fixture/dto/LoginDetailsDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/common/implement/FCMNotificationSenderTest.java
  src/test/java/coffeemeet/server/matching/implement/MatchingQueueCommandTest.java
  src/test/java/coffeemeet/server/matching/implement/MatchingQueueQueryTest.java
  src/test/java/coffeemeet/server/matching/presentation/MatchingControllerTest.java
  src/test/java/coffeemeet/server/matching/service/MatchingServiceTest.java
  src/test/java/coffeemeet/server/user/implement/UserCommandTest.java
  src/test/java/coffeemeet/server/user/implement/UserQueryTest.java
  src/test/java/coffeemeet/server/user/infrastructure/UserRepositoryTest.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
Labels: release

#116 배포 버전 0.5.2
  README.md
  src/main/java/coffeemeet/server/user/domain/Keyword.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: release

#125 채팅방 백업 및 내역 조회 기능 구현
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingMessageCommand.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingRoomCommand.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepository.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingRoomService.java
  src/main/java/coffeemeet/server/chatting/exception/ChattingErrorCode.java
  src/main/java/coffeemeet/server/chatting/history/domain/ChattingMessageHistory.java
  src/main/java/coffeemeet/server/chatting/history/domain/ChattingRoomHistory.java
  src/main/java/coffeemeet/server/chatting/history/domain/UserChattingHistory.java
  src/main/java/coffeemeet/server/chatting/history/implement/ChattingMessageHistoryQuery.java
  src/main/java/coffeemeet/server/chatting/history/implement/ChattingRoomHistoryCommand.java
  src/main/java/coffeemeet/server/chatting/history/implement/ChattingRoomHistoryQuery.java
  src/main/java/coffeemeet/server/chatting/history/implement/UserChattingHistoryQuery.java
  src/main/java/coffeemeet/server/chatting/history/infrastructure/ChattingMessageHistoryQueryRepository.java
  src/main/java/coffeemeet/server/chatting/history/infrastructure/UserChattingHistoryRepository.java
  src/main/java/coffeemeet/server/chatting/history/presentation/ChattingRoomHistoryController.java
  src/main/java/coffeemeet/server/chatting/history/presentation/dto/ChattingMessageHistoriesHTTP.java
  src/main/java/coffeemeet/server/chatting/history/presentation/dto/ChattingRoomHistoriesHTTP.java
  src/main/java/coffeemeet/server/chatting/history/service/ChattingRoomHistoryService.java
  src/main/java/coffeemeet/server/chatting/history/service/dto/ChattingMessageHistoryDto.java
  src/main/java/coffeemeet/server/chatting/history/service/dto/ChattingRoomHistoryDto.java
  src/main/java/coffeemeet/server/common/config/WebConfig.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingMessageCommandTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingRoomCommandTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingRoomServiceTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/ChattingMessageHistoryQueryTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/ChattingRoomHistoryCommandTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/UserChattingHistoryQueryTest.java
  src/test/java/coffeemeet/server/chatting/history/infrastructure/ChattingMessageHistoryQueryRepositoryTest.java
  src/test/java/coffeemeet/server/chatting/history/infrastructure/UserChattingHistoryRepositoryTest.java
  src/test/java/coffeemeet/server/chatting/history/presentation/ChattingRoomHistoryControllerTest.java
  src/test/java/coffeemeet/server/chatting/history/service/ChattingRoomHistoryServiceTest.java
  src/test/java/coffeemeet/server/common/config/RepositoryTestConfig.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
Labels: feat

#118 Feat/#108 신고 기능 구현
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingRoomQuery.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/ChattingRoomRepository.java
  src/main/java/coffeemeet/server/chatting/history/implement/UserChattingHistoryQuery.java
  src/main/java/coffeemeet/server/chatting/history/infrastructure/UserChattingHistoryRepository.java
  src/main/java/coffeemeet/server/common/util/Patterns.java
  src/main/java/coffeemeet/server/matching/implement/MatchingQueueCommand.java
  src/main/java/coffeemeet/server/report/domain/Report.java
  src/main/java/coffeemeet/server/report/domain/ReportAmount.java
  src/main/java/coffeemeet/server/report/domain/ReportPenalty.java
  src/main/java/coffeemeet/server/report/domain/ReportReason.java
  src/main/java/coffeemeet/server/report/exception/ReportErrorCode.java
  src/main/java/coffeemeet/server/report/implement/ReportCommand.java
  src/main/java/coffeemeet/server/report/implement/ReportQuery.java
  src/main/java/coffeemeet/server/report/infrastructure/ReportQueryRepository.java
  src/main/java/coffeemeet/server/report/infrastructure/ReportRepository.java
  src/main/java/coffeemeet/server/report/presentation/ReportController.java
  src/main/java/coffeemeet/server/report/presentation/dto/ReportHTTP.java
  src/main/java/coffeemeet/server/report/service/ReportService.java
  src/main/java/coffeemeet/server/report/service/dto/ReportDetailDto.java
  src/main/java/coffeemeet/server/report/service/dto/ReportDto.java
  src/main/java/coffeemeet/server/report/service/dto/TargetReportDto.java
  src/main/java/coffeemeet/server/user/domain/ReportInfo.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/presentation/dto/SignupHTTP.java
  src/main/java/coffeemeet/server/user/service/UserService.java
  src/test/java/coffeemeet/server/admin/presentation/AdminControllerTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingRoomQueryTest.java
  src/test/java/coffeemeet/server/common/config/RepositoryTestConfig.java
  src/test/java/coffeemeet/server/common/fixture/entity/AdminFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/ReportFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/report/implement/ReportCommandTest.java
  src/test/java/coffeemeet/server/report/implement/ReportQueryTest.java
  src/test/java/coffeemeet/server/report/infrastructure/ReportQueryRepositoryTest.java
  src/test/java/coffeemeet/server/report/infrastructure/ReportRepositoryTest.java
  src/test/java/coffeemeet/server/report/presentation/ReportControllerTest.java
  src/test/java/coffeemeet/server/report/service/ReportServiceTest.java
Labels: feat

#133 Oauth2.0 인증 로직 수정
  src/main/java/coffeemeet/server/chatting/current/service/dto/ChattingDto.java
  src/main/java/coffeemeet/server/chatting/history/service/dto/ChattingMessageHistoryDto.java
  src/main/java/coffeemeet/server/report/service/dto/ReportDetailDto.java
  src/main/java/coffeemeet/server/user/domain/OAuthInfo.java
  src/main/java/coffeemeet/server/user/domain/Profile.java
  src/main/java/coffeemeet/server/user/domain/ReportInfo.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/exception/UserErrorCode.java
  src/main/java/coffeemeet/server/user/implement/UserQuery.java
  src/main/java/coffeemeet/server/user/presentation/UserController.java
  src/main/java/coffeemeet/server/user/presentation/dto/LoginDetailsHTTP.java
  src/main/java/coffeemeet/server/user/presentation/dto/SignupHTTP.java
  src/main/java/coffeemeet/server/user/service/UserService.java
  src/main/java/coffeemeet/server/user/service/dto/LoginDetailsDto.java
  src/main/java/coffeemeet/server/user/service/dto/MyProfileDto.java
  src/main/java/coffeemeet/server/user/service/dto/UserProfileDto.java
  src/test/java/coffeemeet/server/common/fixture/dto/LoginDetailsHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/user/implement/UserQueryTest.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: refactor

#134 배포 버전 0.6.3
  README.md
  src/main/java/coffeemeet/server/certification/domain/Department.java
  src/main/java/coffeemeet/server/certification/presentation/CertificationController.java
  src/main/java/coffeemeet/server/certification/presentation/dto/EmailHTTP.java
  src/main/java/coffeemeet/server/certification/presentation/dto/VerificationCodeHTTP.java
  src/main/java/coffeemeet/server/certification/service/CertificationService.java
  src/main/java/coffeemeet/server/chatting/current/service/dto/ChattingDto.java
  src/main/java/coffeemeet/server/chatting/history/service/dto/ChattingMessageHistoryDto.java
  src/main/java/coffeemeet/server/common/execption/GlobalErrorCode.java
  src/main/java/coffeemeet/server/common/presentation/advice/GlobalExceptionHandler.java
  src/main/java/coffeemeet/server/report/service/dto/ReportDetailDto.java
  src/main/java/coffeemeet/server/user/domain/OAuthInfo.java
  src/main/java/coffeemeet/server/user/domain/Profile.java
  src/main/java/coffeemeet/server/user/domain/ReportInfo.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/exception/UserErrorCode.java
  src/main/java/coffeemeet/server/user/implement/UserQuery.java
  src/main/java/coffeemeet/server/user/presentation/UserController.java
  src/main/java/coffeemeet/server/user/presentation/dto/LoginDetailsHTTP.java
  src/main/java/coffeemeet/server/user/presentation/dto/SignupHTTP.java
  src/main/java/coffeemeet/server/user/service/UserService.java
  src/main/java/coffeemeet/server/user/service/dto/LoginDetailsDto.java
  src/main/java/coffeemeet/server/user/service/dto/MyProfileDto.java
  src/main/java/coffeemeet/server/user/service/dto/UserProfileDto.java
  src/main/resources/application.yml
  src/test/java/coffeemeet/server/certification/presentation/CertificationControllerTest.java
  src/test/java/coffeemeet/server/common/fixture/dto/LoginDetailsHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/CertificationFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/user/implement/UserQueryTest.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: release

#139 문의 도메인
  src/main/java/coffeemeet/server/admin/presentation/AdminController.java
  src/main/java/coffeemeet/server/admin/presentation/dto/AdminCustomSlice.java
  src/main/java/coffeemeet/server/inquiry/domain/Inquiry.java
  src/main/java/coffeemeet/server/inquiry/implement/InquiryCommand.java
  src/main/java/coffeemeet/server/inquiry/implement/InquiryQuery.java
  src/main/java/coffeemeet/server/inquiry/infrastructure/InquiryQueryRepository.java
  src/main/java/coffeemeet/server/inquiry/infrastructure/InquiryRepository.java
  src/main/java/coffeemeet/server/inquiry/presentation/InquiryController.java
  src/main/java/coffeemeet/server/inquiry/presentation/dto/InquiryHTTP.java
  src/main/java/coffeemeet/server/inquiry/service/InquiryService.java
  src/main/java/coffeemeet/server/inquiry/service/dto/InquirySearchResponse.java
  src/test/java/coffeemeet/server/admin/presentation/AdminControllerTest.java
  src/test/java/coffeemeet/server/admin/service/AdminServiceTest.java
  src/test/java/coffeemeet/server/common/config/RepositoryTestConfig.java
  src/test/java/coffeemeet/server/common/fixture/entity/AdminFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/InquiryFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/inquiry/implement/InquiryCommandTest.java
  src/test/java/coffeemeet/server/inquiry/implement/InquiryQueryTest.java
  src/test/java/coffeemeet/server/inquiry/infrastructure/InquiryQueryRepositoryTest.java
  src/test/java/coffeemeet/server/inquiry/presentation/InquiryControllerTest.java
  src/test/java/coffeemeet/server/inquiry/service/InquiryServiceTest.java
Labels: feat

#136 Feat/#128 신고 내역 조회 API 작성
  src/main/java/coffeemeet/server/admin/presentation/AdminController.java
  src/main/java/coffeemeet/server/admin/presentation/dto/AdminCustomPage.java
  src/main/java/coffeemeet/server/common/util/Patterns.java
  src/main/java/coffeemeet/server/report/domain/ReportReason.java
  src/main/java/coffeemeet/server/report/implement/ReportQuery.java
  src/main/java/coffeemeet/server/report/infrastructure/ReportQueryRepository.java
  src/main/java/coffeemeet/server/report/presentation/ReportController.java
  src/main/java/coffeemeet/server/report/presentation/dto/CreateReportHTTP.java
  src/main/java/coffeemeet/server/report/presentation/dto/FindGroupReports.java
  src/main/java/coffeemeet/server/report/presentation/dto/GroupReportHTTP.java
  src/main/java/coffeemeet/server/report/presentation/dto/GroupReportList.java
  src/main/java/coffeemeet/server/report/presentation/dto/ReportDetailHTTP.java
  src/main/java/coffeemeet/server/report/presentation/dto/ReportHTTP.java
  src/main/java/coffeemeet/server/report/presentation/dto/ReportList.java
  src/main/java/coffeemeet/server/report/service/ReportService.java
  src/main/java/coffeemeet/server/report/service/dto/GroupReportDto.java
  src/main/java/coffeemeet/server/report/service/dto/ReportDetailDto.java
  src/main/java/coffeemeet/server/report/service/dto/ReportDto.java
  src/main/java/coffeemeet/server/user/presentation/dto/MyProfileHTTP.java
  src/main/java/coffeemeet/server/user/service/UserService.java
  src/main/java/coffeemeet/server/user/service/dto/MyProfileDto.java
  src/test/java/coffeemeet/server/admin/presentation/AdminControllerTest.java
  src/test/java/coffeemeet/server/common/fixture/dto/GroupReportDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/GroupReportListFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/MyProfileHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/ReportDetailDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/ReportDetailHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/ReportDtoFixture.java
  src/test/java/coffeemeet/server/report/infrastructure/ReportQueryRepositoryTest.java
  src/test/java/coffeemeet/server/report/presentation/ReportControllerTest.java
  src/test/java/coffeemeet/server/report/service/ReportServiceTest.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: feat

#150 refactor: 유저 상태 요청 파라미터 변경
  src/main/java/coffeemeet/server/admin/presentation/AdminController.java
Labels: release

#149 Feat/#143 유저 상태 요청 기능 구현
  src/main/java/coffeemeet/server/admin/presentation/AdminController.java
  src/main/java/coffeemeet/server/matching/implement/MatchingQueueCommand.java
  src/main/java/coffeemeet/server/report/infrastructure/ReportQueryRepository.java
  src/main/java/coffeemeet/server/report/presentation/dto/GroupReportHTTP.java
  src/main/java/coffeemeet/server/report/presentation/dto/GroupReportList.java
  src/main/java/coffeemeet/server/report/presentation/dto/ReportDetailHTTP.java
  src/main/java/coffeemeet/server/report/presentation/dto/ReportList.java
  src/main/java/coffeemeet/server/report/service/ReportService.java
  src/main/java/coffeemeet/server/report/service/dto/GroupReportDto.java
  src/main/java/coffeemeet/server/report/service/dto/ReportDetailDto.java
  src/main/java/coffeemeet/server/report/service/dto/ReportDto.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/presentation/UserController.java
  src/main/java/coffeemeet/server/user/presentation/dto/LoginDetailsHTTP.java
  src/main/java/coffeemeet/server/user/presentation/dto/MyProfileHTTP.java
  src/main/java/coffeemeet/server/user/presentation/dto/UserProfileHTTP.java
  src/main/java/coffeemeet/server/user/presentation/dto/UserStatusHTTP.java
  src/main/java/coffeemeet/server/user/service/UserService.java
  src/main/java/coffeemeet/server/user/service/dto/LoginDetailsDto.java
  src/main/java/coffeemeet/server/user/service/dto/MyProfileDto.java
  src/main/java/coffeemeet/server/user/service/dto/UserProfileDto.java
  src/main/java/coffeemeet/server/user/service/dto/UserStatusDto.java
  src/test/java/coffeemeet/server/admin/presentation/AdminControllerTest.java
  src/test/java/coffeemeet/server/common/fixture/UserStatusDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/GroupReportDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/GroupReportListFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/LoginDetailsDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/LoginDetailsHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/MyProfileDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/MyProfileHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/ReportDetailDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/ReportDetailHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/ReportDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/UserProfileDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/UserProfileHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/UserStatusHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/report/service/ReportServiceTest.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: feat

#145 Feat/#144 유저 상태 변경 로직 구현 및 세션 저장소 구조 변경
  src/main/java/coffeemeet/server/chatting/current/domain/ChattingSession.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingSessionCommand.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingSessionQuery.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/ChattingSessionRepository.java
  src/main/java/coffeemeet/server/chatting/current/infrastructure/MemoryChattingSessionRepository.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingMessageService.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/implement/UserCommand.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingSessionCommandTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingSessionQueryTest.java
  src/test/java/coffeemeet/server/chatting/current/infrastructure/MemoryChattingSessionRepositoryTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingMessageServiceTest.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
  src/test/java/coffeemeet/server/user/implement/UserCommandTest.java
Labels: feat

#152 관리자 문의 상세 조회 및 확인 처리 API 작성
  src/main/java/coffeemeet/server/admin/presentation/AdminController.java
  src/main/java/coffeemeet/server/admin/service/AdminService.java
  src/main/java/coffeemeet/server/inquiry/exception/InquiryErrorCode.java
  src/main/java/coffeemeet/server/inquiry/implement/InquiryCommand.java
  src/main/java/coffeemeet/server/inquiry/implement/InquiryQuery.java
  src/main/java/coffeemeet/server/inquiry/presentation/dto/InquiryDetailHTTP.java
  src/main/java/coffeemeet/server/inquiry/service/InquiryService.java
  src/main/java/coffeemeet/server/inquiry/service/dto/InquiryDetailDto.java
  src/main/resources/application.yml
  src/test/java/coffeemeet/server/admin/presentation/AdminControllerTest.java
  src/test/java/coffeemeet/server/admin/service/AdminServiceTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingMessageServiceTest.java
  src/test/java/coffeemeet/server/common/fixture/UserStatusDtoFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/UserStatusHTTPFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/InquiryFixture.java
  src/test/java/coffeemeet/server/inquiry/implement/InquiryCommandTest.java
  src/test/java/coffeemeet/server/inquiry/implement/InquiryQueryTest.java
  src/test/java/coffeemeet/server/inquiry/service/InquiryServiceTest.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: feat

#154 배포 버전 0.8.4
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/presentation/dto/UserStatusHTTP.java
  src/test/java/coffeemeet/server/common/fixture/entity/CertificationFixture.java
Labels: release

#158 Refactor/#155 신고 조회 응답값 변경
  src/main/java/coffeemeet/server/admin/presentation/AdminController.java
  src/main/java/coffeemeet/server/report/service/ReportService.java
  src/main/java/coffeemeet/server/report/service/dto/GroupReportDto.java
  src/main/java/coffeemeet/server/report/service/dto/ReportDto.java
  src/test/java/coffeemeet/server/admin/presentation/AdminControllerTest.java
Labels: refactor

#156 Test/#119 테스트 코드 수정
  src/main/java/coffeemeet/server/user/service/UserService.java
  src/main/java/coffeemeet/server/user/service/dto/MyProfileDto.java
  src/main/java/coffeemeet/server/user/service/dto/UserProfileDto.java
  src/test/java/coffeemeet/server/common/config/ControllerTestConfig.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: test
