Repository coffee-meet/backend, pull requests merged in 2023-12, with the labels that each got.

#173 배포 버전 0.9.7
  build.gradle
  lombok.config
  src/main/java/coffeemeet/server/admin/presentation/AdminController.java
  src/main/java/coffeemeet/server/chatting/current/implement/ChattingRoomQuery.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingRoomController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/dto/ChatRoomStatusHTTP.java
  src/main/java/coffeemeet/server/chatting/current/service/ChattingRoomService.java
  src/main/java/coffeemeet/server/chatting/current/service/dto/ChatRoomStatusDto.java
  src/main/java/coffeemeet/server/common/implement/FCMNotificationSender.java
  src/main/java/coffeemeet/server/common/presentation/advice/GlobalExceptionHandler.java
  src/main/java/coffeemeet/server/report/presentation/dto/GroupReportHTTP.java
  src/main/java/coffeemeet/server/report/presentation/dto/GroupReportList.java
  src/main/java/coffeemeet/server/report/presentation/dto/ReportList.java
  src/main/java/coffeemeet/server/report/presentation/dto/ReportListHTTP.java
  src/main/java/coffeemeet/server/report/service/ReportService.java
  src/main/java/coffeemeet/server/report/service/dto/ReportListDto.java
  src/main/java/coffeemeet/server/user/domain/User.java
  src/main/java/coffeemeet/server/user/service/UserService.java
  src/test/java/coffeemeet/server/admin/presentation/AdminControllerTest.java
  src/test/java/coffeemeet/server/chatting/concurrency/ChattingMessageServiceConcurrencyTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingRoomQueryTest.java
  src/test/java/coffeemeet/server/chatting/current/presentation/ChattingRoomControllerTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingRoomServiceTest.java
  src/test/java/coffeemeet/server/common/fixture/dto/GroupReportListFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/ChattingFixture.java
  src/test/java/coffeemeet/server/common/fixture/entity/UserFixture.java
  src/test/java/coffeemeet/server/report/service/ReportServiceTest.java
  src/test/java/coffeemeet/server/user/implement/UserCommandTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: release

#179 배포 버전 0.10.7
  src/main/java/coffeemeet/server/chatting/current/service/ChattingMessageService.java
Labels: release

#185 마이페이지 조회 API 응답 데이터 추가
  src/main/java/coffeemeet/server/user/presentation/dto/MyProfileHTTP.java
  src/main/java/coffeemeet/server/user/service/dto/MyProfileDto.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingMessageServiceTest.java
  src/test/java/coffeemeet/server/common/fixture/dto/MyProfileHTTPFixture.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
Labels: refactor

#186 배포 버전 0.10.8
  src/main/java/coffeemeet/server/certification/presentation/CertificationController.java
  src/main/java/coffeemeet/server/certification/service/CertificationService.java
  src/main/java/coffeemeet/server/common/domain/KeyType.java
  src/main/java/coffeemeet/server/common/implement/S3MediaManager.java
  src/main/java/coffeemeet/server/user/presentation/dto/MyProfileHTTP.java
  src/main/java/coffeemeet/server/user/service/dto/MyProfileDto.java
  src/test/java/coffeemeet/server/certification/presentation/CertificationControllerTest.java
  src/test/java/coffeemeet/server/certification/service/CertificationServiceTest.java
  src/test/java/coffeemeet/server/chatting/concurrency/ChattingMessageServiceConcurrencyTest.java
  src/test/java/coffeemeet/server/chatting/current/service/ChattingMessageServiceTest.java
  src/test/java/coffeemeet/server/common/fixture/dto/MyProfileHTTPFixture.java
  src/test/java/coffeemeet/server/user/presentation/UserControllerTest.java
  src/test/java/coffeemeet/server/user/service/UserServiceTest.java
Labels: feat

#189 성능 측정 AOP 설정
  src/main/java/coffeemeet/server/admin/presentation/AdminController.java
  src/main/java/coffeemeet/server/common/annotation/PerformanceMeasurement.java
  src/main/java/coffeemeet/server/common/aop/PerformanceAspect.java
  src/main/resources/application.yml
Labels: feat

#192 배포 0.10.10
  src/main/java/coffeemeet/server/admin/presentation/AdminController.java
  src/main/java/coffeemeet/server/chatting/current/presentation/ChattingMessageController.java
  src/main/java/coffeemeet/server/common/annotation/PerformanceMeasurement.java
  src/main/java/coffeemeet/server/common/aop/PerformanceAspect.java
  src/main/java/coffeemeet/server/user/presentation/UserController.java
  src/main/resources/application.yml
Labels: release

#191 Test/#120 누락된 테스트 코드 작성
  src/main/java/coffeemeet/server/oauth/implement/provider/naver/NaverAuthCodeRequestUrlProvider.java
  src/test/java/coffeemeet/server/admin/implement/AdminQueryTest.java
  src/test/java/coffeemeet/server/admin/service/AdminServiceTest.java
  src/test/java/coffeemeet/server/auth/implement/RefreshTokenCommandTest.java
  src/test/java/coffeemeet/server/auth/implement/RefreshTokenQueryTest.java
  src/test/java/coffeemeet/server/auth/service/AuthServiceTest.java
  src/test/java/coffeemeet/server/certification/implement/CertificationCommandTest.java
  src/test/java/coffeemeet/server/certification/implement/CertificationQueryTest.java
  src/test/java/coffeemeet/server/certification/implement/EmailVerificationCommandTest.java
  src/test/java/coffeemeet/server/certification/implement/EmailVerificationQueryTest.java
  src/test/java/coffeemeet/server/certification/infrastructure/CertificationRepositoryTest.java
  src/test/java/coffeemeet/server/certification/service/CertificationServiceTest.java
  src/test/java/coffeemeet/server/chatting/current/infrastructure/ChattingMessageQueryRepositoryTest.java
  src/test/java/coffeemeet/server/chatting/history/implement/ChattingRoomHistoryQueryTest.java
  src/test/java/coffeemeet/server/common/fixture/dto/NaverMemberResponseFixture.java
  src/test/java/coffeemeet/server/common/fixture/dto/NaverTokenFixture.java
  src/test/java/coffeemeet/server/matching/implement/MatchingQueueCommandTest.java
  src/test/java/coffeemeet/server/oauth/implement/client/kakao/KakaoMemberClientTest.java
  src/test/java/coffeemeet/server/oauth/implement/client/naver/NaverMemberClientTest.java
  src/test/java/coffeemeet/server/oauth/implement/provider/kakao/KakaoAuthCodeRequestUrlProviderTest.java
  src/test/java/coffeemeet/server/oauth/implement/provider/naver/NaverAuthCodeRequestUrlProviderTest.java
  src/test/java/coffeemeet/server/oauth/infrastructure/kakao/KakaoClientTest.java
  src/test/java/coffeemeet/server/oauth/infrastructure/naver/NaverClientTest.java
  src/test/java/coffeemeet/server/report/implement/ReportCommandTest.java
  src/test/java/coffeemeet/server/report/implement/ReportQueryTest.java
  src/test/java/coffeemeet/server/report/infrastructure/ReportQueryRepositoryTest.java
  src/test/java/coffeemeet/server/report/service/ReportServiceTest.java
  src/test/java/coffeemeet/server/user/implement/InterestCommandTest.java
  src/test/java/coffeemeet/server/user/implement/InterestQueryTest.java
  src/test/java/coffeemeet/server/user/implement/UserQueryTest.java
Labels: test

#197 Test/#195 유저 도메인 테스트 코드 작성
  src/test/java/coffeemeet/server/user/domain/BirthTest.java
  src/test/java/coffeemeet/server/user/domain/EmailTest.java
  src/test/java/coffeemeet/server/user/domain/InterestTest.java
  src/test/java/coffeemeet/server/user/domain/OAuthInfoTest.java
  src/test/java/coffeemeet/server/user/domain/OAuthProviderTest.java
  src/test/java/coffeemeet/server/user/domain/ProfileTest.java
  src/test/java/coffeemeet/server/user/domain/ReportInfoTest.java
  src/test/java/coffeemeet/server/user/domain/UserStatusTest.java
  src/test/java/coffeemeet/server/user/domain/UserTest.java
Labels: test

#199 docs: 리드미 작성
  README.md
Labels: docs

#200 Docs/#172
  README.md
  img/기술스택.png
Labels: docs

#201 리드미 작성
  README.md
  img/기술스택.png
  img/매칭.png
  img/인증.png
  img/채팅.png
Labels: release

#196 채팅 관련 테스트 코드 리팩토링
  src/main/java/coffeemeet/server/common/presentation/resolver/UserArgumentResolver.java
  src/main/java/coffeemeet/server/matching/service/MatchingService.java
  src/main/java/coffeemeet/server/user/implement/UserQuery.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingRoomQueryTest.java
  src/test/java/coffeemeet/server/chatting/current/implement/ChattingSessionQueryTest.java
  src/test/java/coffeemeet/server/oauth/implement/client/naver/NaverMemberClientTest.java
  src/test/java/coffeemeet/server/oauth/infrastructure/kakao/KakaoClientTest.java
  src/test/java/coffeemeet/server/oauth/infrastructure/naver/NaverClientTest.java
  src/test/java/coffeemeet/server/user/domain/OAuthInfoTest.java
  src/test/java/coffeemeet/server/user/domain/UserTest.java
  src/test/java/coffeemeet/server/user/implement/InterestCommandTest.java
  src/test/java/coffeemeet/server/user/implement/UserQueryTest.java
Labels: test

#216 이전 채팅방 조회 캐싱 적용
  build.gradle
  src/main/java/coffeemeet/server/chatting/history/service/ChattingRoomHistoryService.java
  src/main/java/coffeemeet/server/chatting/history/service/dto/ChattingHistory.java
  src/main/java/coffeemeet/server/common/config/RedisCacheConfig.java
  src/main/resources/application.yml
  src/test/java/coffeemeet/server/report/service/ReportServiceTest.java
Labels: refactor
